[project]
name = "quackengine"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "chess>=1.11.2",
    "pytest>=8.3.5",
    "ruff==0.14",
]

[tool.ruff.lint]
select = ["E", "F", "B", "N"]
ignore = ["E501"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
